# Generated by Django 5.2.9 on 2026-03-20 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("label", models.CharField(max_length=200)),
                ("agent_count", models.IntegerField(default=0)),
                ("growth_rate", models.FloatField(default=0)),
                ("new_agents_30d", models.IntegerField(default=0)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Agent Categories",
                "ordering": ["-agent_count"],
            },
        ),
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("name", models.CharField(db_index=True, max_length=300)),
                ("category_name", models.CharField(blank=True, max_length=200)),
                ("industry", models.CharField(blank=True, max_length=200)),
                (
                    "access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Open Source", "Open Source"),
                            ("Closed Source", "Closed Source"),
                            ("API", "API"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Free", "Free"),
                            ("Freemium", "Freemium"),
                            ("Paid", "Paid"),
                        ],
                        max_length=50,
                    ),
                ),
                ("short_description", models.TextField(blank=True)),
                ("long_description", models.TextField(blank=True)),
                ("key_features", models.JSONField(default=list)),
                ("use_cases", models.JSONField(default=list)),
                ("logo_url", models.URLField(blank=True, max_length=500)),
                ("image_url", models.URLField(blank=True, max_length=500)),
                ("video_url", models.URLField(blank=True, max_length=500)),
                ("popularity_score", models.IntegerField(db_index=True, default=0)),
                ("upvotes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("bookmark_count", models.IntegerField(default=0)),
                ("review_count", models.IntegerField(default=0)),
                ("average_rating", models.FloatField(default=0)),
                ("views_24h", models.IntegerField(default=0)),
                ("views_7d", models.IntegerField(default=0)),
                ("views_30d", models.IntegerField(default=0)),
                ("upvotes_24h", models.IntegerField(default=0)),
                ("upvotes_7d", models.IntegerField(default=0)),
                ("upvotes_30d", models.IntegerField(default=0)),
                ("website", models.URLField(blank=True, max_length=500)),
                ("github_url", models.URLField(blank=True, max_length=500)),
                ("twitter_url", models.URLField(blank=True, max_length=500)),
                ("linkedin_url", models.URLField(blank=True, max_length=500)),
                ("discord_url", models.URLField(blank=True, max_length=500)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_featured", models.BooleanField(default=False)),
                ("seo_boost", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(default="aiagentsdirectory", max_length=100),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="agents.agentcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Agent",
                "verbose_name_plural": "AI Agents",
                "ordering": ["-popularity_score"],
                "indexes": [
                    models.Index(
                        fields=["category", "-popularity_score"],
                        name="agents_aiag_categor_afdbd6_idx",
                    ),
                    models.Index(
                        fields=["pricing_model"], name="agents_aiag_pricing_ed3223_idx"
                    ),
                    models.Index(
                        fields=["access"], name="agents_aiag_access_6527b2_idx"
                    ),
                ],
            },
        ),
    ]
