services:
  web:
    build: .
    container_name: web
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    expose:
      - "8000"
    env_file:
      - .env

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    expose:
      - "5678"
    volumes:
      - n8n_data:/home/node/.n8n

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    depends_on:
      - web
      - n8n

volumes:
  static_volume:
  media_volume:
  n8n_data:
