version: "3.8"

services:
  backend:
    build: .
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --workers 3 --bind 0.0.0.0:8000 config.wsgi:application"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/backend/staticfiles
      - media_volume:/app/backend/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
