upstream backend {
    server backend:8000;
}

upstream n8n {
    server localhost:5678;
}

server {
    listen 80;
    server_name api.one9founders.com;

    location / {
        proxy_pass http://backend;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /app/backend/staticfiles/;
    }

    location /media/ {
        alias /app/backend/media/;
    }
}

server {
    listen 80;
    server_name n8n.one9founders.com;

    location / {
        proxy_pass http://n8n;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
