# Generated by Django 5.2.9 on 2025-12-25 13:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
