# Generated by Django 5.2.9 on 2025-12-27 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_review_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="free_tier_available",
        ),
    ]
