# Generated by Django 5.2.9 on 2025-12-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_tool_free_tier_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="free_tier_available",
            field=models.BooleanField(default=False),
        ),
    ]
