# Generated by Django 5.2.9 on 2026-01-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_update_embedding_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="pricing_type",
            field=models.CharField(
                choices=[("free", "Free"), ("freemium", "Freemium"), ("paid", "Paid")],
                db_index=True,
                default="freemium",
                help_text="Primary pricing type: free, freemium, or paid",
                max_length=20,
            ),
        ),
    ]
