# Generated by Django 5.2.9 on 2026-01-26 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_add_pricing_type_to_tool"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "db_table": "pipeline_config",
            },
        ),
        migrations.CreateModel(
            name="QualifiedNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance_score",
                    models.IntegerField(
                        db_index=True, default=0, help_text="AI relevance score 0-100"
                    ),
                ),
                (
                    "founder_relevance",
                    models.IntegerField(
                        default=0, help_text="Relevance to founders 0-100"
                    ),
                ),
                (
                    "practical_impact",
                    models.IntegerField(
                        default=0, help_text="Practical impact score 0-100"
                    ),
                ),
                (
                    "novelty_score",
                    models.IntegerField(default=0, help_text="Novelty score 0-100"),
                ),
                (
                    "scoring_rationale",
                    models.TextField(blank=True, help_text="AI explanation"),
                ),
                (
                    "scoring_model",
                    models.CharField(default="gpt-4o-mini", max_length=50),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scored", "Scored"),
                            ("auto_rejected", "Auto Rejected"),
                            ("queued", "Queued for Review"),
                            ("auto_approved", "Auto Approved"),
                            ("manually_approved", "Manually Approved"),
                            ("manually_rejected", "Manually Rejected"),
                        ],
                        db_index=True,
                        default="scored",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "qualified_news_items",
                "ordering": ["-relevance_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_type",
                    models.CharField(
                        choices=[
                            ("scrape", "Scraping"),
                            ("score", "Scoring"),
                            ("generate", "Content Generation"),
                            ("publish", "Publishing"),
                            ("full", "Full Pipeline"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=50)),
                (
                    "batch_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("items_processed", models.IntegerField(default=0)),
                ("items_succeeded", models.IntegerField(default=0)),
                ("items_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("logs", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "pipeline_runs",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["run_type", "status"],
                        name="pipeline_ru_run_typ_00ad5e_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="pipeline_ru_started_ab0c06_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewsDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "excerpt",
                    models.TextField(help_text="Short preview/hook", max_length=300),
                ),
                ("content", models.TextField(help_text="Full article content (HTML)")),
                ("hook", models.TextField(blank=True, help_text="Opening hook")),
                (
                    "why_matters",
                    models.TextField(blank=True, help_text="Why this matters section"),
                ),
                (
                    "founder_takeaway",
                    models.TextField(blank=True, help_text="Key takeaway"),
                ),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                ("featured_image", models.URLField(blank=True)),
                (
                    "generation_model",
                    models.CharField(default="gpt-4o-mini", max_length=50),
                ),
                (
                    "generation_prompt_version",
                    models.CharField(default="v1", max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("generated", "Generated"),
                            ("editing", "Editing"),
                            ("ready", "Ready to Publish"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Generation Failed"),
                        ],
                        db_index=True,
                        default="generating",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                (
                    "scheduled_for",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qualified_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft",
                        to="api.qualifiednewsitem",
                    ),
                ),
            ],
            options={
                "db_table": "news_drafts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("producthunt", "Product Hunt"),
                            ("taaft", "There's An AI For That"),
                            ("futurepedia", "Futurepedia"),
                            ("huggingface", "Hugging Face"),
                            ("manual", "Manual Entry"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("source_url", models.URLField(max_length=500)),
                ("external_url", models.URLField(blank=True, max_length=500)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("images", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA256 hash for dedup",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scraped", "Scraped"),
                            ("processing", "Processing"),
                            ("qualified", "Qualified"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="scraped",
                        max_length=20,
                    ),
                ),
                ("status_reason", models.TextField(blank=True)),
                (
                    "scrape_batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Batch ID for idempotency",
                        max_length=100,
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "raw_scraped_items",
                "ordering": ["-scraped_at"],
                "indexes": [
                    models.Index(
                        fields=["source", "status"],
                        name="raw_scraped_source_17b819_idx",
                    ),
                    models.Index(
                        fields=["scraped_at", "status"],
                        name="raw_scraped_scraped_52fef6_idx",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="qualifiednewsitem",
            name="scraped_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qualified_item",
                to="api.scrapeditem",
            ),
        ),
        migrations.CreateModel(
            name="PublishedArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("original_url", models.URLField(max_length=500)),
                ("relevance_score", models.IntegerField(default=0)),
                (
                    "published_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "publish_slot",
                    models.IntegerField(
                        default=1, help_text="Which slot of the day (1-5)"
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("engagement_score", models.FloatField(default=0.0)),
                (
                    "draft",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published",
                        to="api.newsdraft",
                    ),
                ),
                (
                    "news",
                    models.OneToOneField(
                        help_text="Link to main News model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_article",
                        to="api.news",
                    ),
                ),
            ],
            options={
                "db_table": "published_articles",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["published_at", "source"],
                        name="published_a_publish_b5c62b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="newsdraft",
            index=models.Index(
                fields=["status", "-created_at"], name="news_drafts_status_b4381f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="newsdraft",
            index=models.Index(
                fields=["scheduled_for", "status"],
                name="news_drafts_schedul_95ecd1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qualifiednewsitem",
            index=models.Index(
                fields=["status", "-relevance_score"],
                name="qualified_n_status_abc4b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qualifiednewsitem",
            index=models.Index(
                fields=["created_at", "status"], name="qualified_n_created_ed9b82_idx"
            ),
        ),
    ]
