# Generated by Django 5.2.9 on 2026-01-26 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_add_tracking_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="upvote_count",
            field=models.IntegerField(default=0, help_text="Number of upvotes"),
        ),
        migrations.CreateModel(
            name="NewsUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="For anonymous upvotes",
                        max_length=255,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="api.news",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "news_upvotes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["news", "-created_at"],
                        name="news_upvote_news_id_0a8642_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("user__isnull", False)),
                        fields=("news", "user"),
                        name="unique_user_upvote",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("session_id__gt", "")),
                        fields=("news", "session_id"),
                        name="unique_session_upvote",
                    ),
                ],
            },
        ),
    ]
