# Generated by Django 5.2.9 on 2026-01-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_news_upvote_count_newsupvote"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="featured_image_upload",
            field=models.ImageField(
                blank=True,
                help_text="Upload image directly (will be used if no URL provided)",
                null=True,
                upload_to="news/images/",
            ),
        ),
    ]
