# Generated by Django 5.2.9 on 2026-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_tool_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="landing_page_screenshot",
            field=models.URLField(
                blank=True,
                help_text="Screenshot/preview of the tool's landing page",
                null=True,
            ),
        ),
    ]
