# Generated by Django 5.2.9 on 2026-02-28 01:01

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_add_landing_page_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("content", django_summernote.fields.SummernoteTextField(blank=True)),
                ("featured_image", models.URLField(blank=True)),
                ("author", models.CharField(default="One9Founders", max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '30 min', '2 hours', '1-2 hours'",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai-fundamentals", "AI Fundamentals"),
                            ("machine-learning", "Machine Learning"),
                            (
                                "natural-language-processing",
                                "Natural Language Processing",
                            ),
                            ("computer-vision", "Computer Vision"),
                            ("automation", "Automation"),
                            ("data-analytics", "Data & Analytics"),
                            ("marketing", "Marketing"),
                            ("product-development", "Product Development"),
                            ("sales", "Sales"),
                            ("operations", "Operations"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="ai-fundamentals",
                        max_length=50,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("founders", "Founders"),
                            ("developers", "Developers"),
                            ("marketers", "Marketers"),
                            ("product-managers", "Product Managers"),
                            ("designers", "Designers"),
                            ("non-technical", "Non-Technical"),
                            ("everyone", "Everyone"),
                        ],
                        db_index=True,
                        default="founders",
                        max_length=30,
                    ),
                ),
                (
                    "pricing",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("paid", "Paid"),
                            ("freemium", "Freemium"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in USD (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars). Falls back to title if blank.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars). Falls back to short_description.",
                        max_length=160,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manually set 'last updated' date for content freshness",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tools_used",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AI tools referenced or used in this content",
                        related_name="%(class)s_content",
                        to="api.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Guide",
                "verbose_name_plural": "Guides",
                "db_table": "guides",
                "ordering": ["-published_at", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("content", django_summernote.fields.SummernoteTextField(blank=True)),
                ("featured_image", models.URLField(blank=True)),
                ("author", models.CharField(default="One9Founders", max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '30 min', '2 hours', '1-2 hours'",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai-fundamentals", "AI Fundamentals"),
                            ("machine-learning", "Machine Learning"),
                            (
                                "natural-language-processing",
                                "Natural Language Processing",
                            ),
                            ("computer-vision", "Computer Vision"),
                            ("automation", "Automation"),
                            ("data-analytics", "Data & Analytics"),
                            ("marketing", "Marketing"),
                            ("product-development", "Product Development"),
                            ("sales", "Sales"),
                            ("operations", "Operations"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="ai-fundamentals",
                        max_length=50,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("founders", "Founders"),
                            ("developers", "Developers"),
                            ("marketers", "Marketers"),
                            ("product-managers", "Product Managers"),
                            ("designers", "Designers"),
                            ("non-technical", "Non-Technical"),
                            ("everyone", "Everyone"),
                        ],
                        db_index=True,
                        default="founders",
                        max_length=30,
                    ),
                ),
                (
                    "pricing",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("paid", "Paid"),
                            ("freemium", "Freemium"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in USD (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars). Falls back to title if blank.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars). Falls back to short_description.",
                        max_length=160,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manually set 'last updated' date for content freshness",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tools_used",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AI tools referenced or used in this content",
                        related_name="%(class)s_content",
                        to="api.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab",
                "verbose_name_plural": "Labs",
                "db_table": "labs",
                "ordering": ["-published_at", "-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("content", django_summernote.fields.SummernoteTextField(blank=True)),
                ("featured_image", models.URLField(blank=True)),
                ("author", models.CharField(default="One9Founders", max_length=255)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '30 min', '2 hours', '1-2 hours'",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai-fundamentals", "AI Fundamentals"),
                            ("machine-learning", "Machine Learning"),
                            (
                                "natural-language-processing",
                                "Natural Language Processing",
                            ),
                            ("computer-vision", "Computer Vision"),
                            ("automation", "Automation"),
                            ("data-analytics", "Data & Analytics"),
                            ("marketing", "Marketing"),
                            ("product-development", "Product Development"),
                            ("sales", "Sales"),
                            ("operations", "Operations"),
                            ("security", "Security"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="ai-fundamentals",
                        max_length=50,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("founders", "Founders"),
                            ("developers", "Developers"),
                            ("marketers", "Marketers"),
                            ("product-managers", "Product Managers"),
                            ("designers", "Designers"),
                            ("non-technical", "Non-Technical"),
                            ("everyone", "Everyone"),
                        ],
                        db_index=True,
                        default="founders",
                        max_length=30,
                    ),
                ),
                (
                    "pricing",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("paid", "Paid"),
                            ("freemium", "Freemium"),
                        ],
                        db_index=True,
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price in USD (if applicable)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="SEO title (max 70 chars). Falls back to title if blank.",
                        max_length=70,
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO description (max 160 chars). Falls back to short_description.",
                        max_length=160,
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="Manually set 'last updated' date for content freshness",
                        null=True,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tools_used",
                    models.ManyToManyField(
                        blank=True,
                        help_text="AI tools referenced or used in this content",
                        related_name="%(class)s_content",
                        to="api.tool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "db_table": "workshops",
                "ordering": ["-published_at", "-created_at"],
                "abstract": False,
            },
        ),
    ]
