# Generated by Django 5.2.9 on 2026-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_seed_chatgpt_business_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_startup",
            field=models.BooleanField(
                default=False, help_text="Whether the user is a startup founder"
            ),
        ),
    ]
