# Generated by Django 5.2.9 on 2026-03-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_add_is_startup_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="security_assessed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the security assessment was last performed",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="security_score",
            field=models.IntegerField(
                blank=True,
                help_text="Security score from 0-100 based on 10-point assessment",
                null=True,
            ),
        ),
    ]
