# Generated by Django 5.2.9 on 2026-03-10 07:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_add_security_fields_to_tool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="security_score",
            field=models.IntegerField(
                blank=True,
                help_text="Security score from 0-100 based on 10-point assessment",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
