# Generated by Django 6.0.3 on 2026-03-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_add_security_score_validators"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolSentimentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Unknown",
                        help_text="e.g., G2, Reddit, X",
                        max_length=50,
                    ),
                ),
                ("weighted_score", models.FloatField()),
                ("raw_aspect_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_logs",
                        to="api.tool",
                    ),
                ),
            ],
            options={
                "db_table": "tool_sentiment_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tool", "-created_at"],
                        name="tool_sentim_tool_id_87ec0f_idx",
                    )
                ],
            },
        ),
    ]
