# Generated by Django 5.2.9 on 2026-03-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_toolsentimentlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ToolSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(db_index=True, max_length=255)),
                (
                    "suggested_by",
                    models.CharField(
                        blank=True, default="extension_user", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tool_suggestions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="tool",
            name="domain",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Root domain extracted from website URL (e.g. runway.ml)",
                max_length=255,
                null=True,
            ),
        ),
    ]
