# Generated by Django 5.2.9 on 2026-03-19 21:23

from urllib.parse import urlparse

from django.db import migrations


def populate_domain(apps, schema_editor):
    Tool = apps.get_model("api", "Tool")
    tools = Tool.objects.filter(website__isnull=False).exclude(website="")
    updated = []
    for tool in tools.iterator():
        try:
            parsed = urlparse(tool.website)
            hostname = parsed.hostname or ""
            domain = hostname.lower().removeprefix("www.")
            if domain:
                tool.domain = domain
                updated.append(tool)
        except Exception:
            continue
    if updated:
        Tool.objects.bulk_update(updated, ["domain"], batch_size=500)


def reverse_populate_domain(apps, schema_editor):
    Tool = apps.get_model("api", "Tool")
    Tool.objects.all().update(domain=None)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_add_domain_and_tool_suggestion"),
    ]

    operations = [
        migrations.RunPython(populate_domain, reverse_populate_domain),
    ]
