# Generated by Django 5.2.9 on 2026-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_discovery_run_and_last_enriched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='entry_type',
            field=models.CharField(choices=[('product', 'Product'), ('gpt_store', 'ChatGPT store listing'), ('app_listing', 'App store listing'), ('extension', 'Browser extension'), ('marketplace', 'Marketplace / template listing'), ('no_url', 'No website')], db_index=True, default='product', help_text="What this row actually is: a product with its own site, or a listing on someone else's platform (ChatGPT store, app store).", max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='hygiene_flags',
            field=models.JSONField(blank=True, default=list, help_text='Name/content quality flags raised by the hygiene pass.'),
        ),
        migrations.AddField(
            model_name='tool',
            name='last_hygiene_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the hygiene pass last revised this row.', null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='link_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='link_final_url',
            field=models.URLField(blank=True, help_text='Where the website URL actually resolved to, after redirects.', max_length=500),
        ),
        migrations.AddField(
            model_name='tool',
            name='link_status',
            field=models.CharField(choices=[('ok', 'OK'), ('redirected', 'Redirected'), ('broken', 'Broken (4xx/5xx)'), ('unreachable', 'Unreachable (DNS/timeout)'), ('parked', 'Parked or payment-walled'), ('malformed', 'Malformed URL'), ('unchecked', 'Not checked')], db_index=True, default='unchecked', help_text='Result of the last website reachability check.', max_length=20),
        ),
        migrations.AddField(
            model_name='tool',
            name='popularity_score',
            field=models.DecimalField(db_index=True, decimal_places=4, default=0, help_text='0-1 blended popularity score used for ranking.', max_digits=6),
        ),
    ]
