# Generated by Django 5.2.9 on 2026-09-12 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_external_tool_candidate_and_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externaltoolcandidate",
            name="source",
            field=models.CharField(
                choices=[
                    ("official", "Official website"),
                    ("producthunt", "Product Hunt"),
                    ("taaft", "There's An AI For That"),
                    ("g2", "G2"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("hackernews", "Hacker News"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="toolsource",
            name="source",
            field=models.CharField(
                choices=[
                    ("official", "Official website"),
                    ("producthunt", "Product Hunt"),
                    ("taaft", "There's An AI For That"),
                    ("g2", "G2"),
                    ("linkedin", "LinkedIn"),
                    ("github", "GitHub"),
                    ("hackernews", "Hacker News"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="ToolFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(db_index=True, max_length=64)),
                ("value", models.JSONField()),
                (
                    "source_name",
                    models.CharField(default="Official website", max_length=120),
                ),
                ("source_url", models.URLField(max_length=500)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                (
                    "observed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sourced_facts",
                        to="api.tool",
                    ),
                ),
            ],
            options={
                "db_table": "tool_facts",
                "ordering": ["field_name", "-observed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tool", "field_name", "source_url"),
                        name="uniq_tool_fact_source",
                    )
                ],
            },
        ),
    ]
