# Generated by Django 5.2.9 on 2026-09-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_toolsubmission_listed_email_sent_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.UUIDField(unique=True)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('entity_slug', models.CharField(blank=True, max_length=255)),
                ('surface', models.CharField(blank=True, max_length=64)),
                ('result_position', models.PositiveIntegerField(blank=True, null=True)),
                ('query_id', models.CharField(blank=True, max_length=64)),
                ('campaign', models.CharField(blank=True, max_length=128)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('counts_for_ranking', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'catalog_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.CharField(choices=[('workflow_audit', 'Workflow audit'), ('implementation', 'Scoped implementation'), ('maintenance', 'Maintenance')], db_index=True, max_length=32)),
                ('workflow', models.TextField()),
                ('current_tools', models.TextField(blank=True)),
                ('team_context', models.TextField(blank=True)),
                ('desired_outcome', models.TextField()),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('closed', 'Closed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service inquiries',
                'db_table': 'service_inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='toolclick',
            name='campaign',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='toolclick',
            name='counts_for_ranking',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='toolclick',
            name='event_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='toolclick',
            name='query_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='toolclick',
            name='result_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toolclick',
            name='surface',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='toolsubmission',
            name='enrichment_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toolsubmission',
            name='enrichment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='toolsubmission',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='toolsubmission',
            name='public_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='toolclick',
            index=models.Index(fields=['counts_for_ranking', '-created_at'], name='tool_clicks_counts__ed5821_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogevent',
            index=models.Index(fields=['event_name', '-created_at'], name='catalog_eve_event_n_a1ac43_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogevent',
            index=models.Index(fields=['entity_type', 'entity_slug'], name='catalog_eve_entity__79e749_idx'),
        ),
    ]
