# Generated by Django 5.2.9 on 2026-03-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arxiv_id",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("title", models.TextField()),
                ("abstract", models.TextField()),
                ("authors", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
                ("published_at", models.DateTimeField()),
                ("updated_at_arxiv", models.DateTimeField(blank=True, null=True)),
                ("pdf_url", models.URLField()),
                ("arxiv_url", models.URLField()),
                ("hf_url", models.URLField(blank=True)),
                ("code_url", models.URLField(blank=True)),
                ("demo_url", models.URLField(blank=True)),
                ("hf_upvotes", models.IntegerField(default=0)),
                ("citation_count", models.IntegerField(default=0)),
                ("ai_summary", models.TextField(blank=True)),
                ("ai_tags", models.JSONField(default=list)),
                (
                    "ai_difficulty",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_enriched", models.BooleanField(default=False)),
                ("is_trending", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "research_papers",
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["-published_at"], name="research_pa_publish_df76c2_idx"
                    ),
                    models.Index(
                        fields=["-hf_upvotes"], name="research_pa_hf_upvo_0c8d63_idx"
                    ),
                    models.Index(
                        fields=["is_trending"], name="research_pa_is_tren_a9247a_idx"
                    ),
                    models.Index(
                        fields=["is_enriched"], name="research_pa_is_enri_283d4a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=300)),
                ("paper_count", models.IntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "papers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="author_records",
                        to="research_papers.paper",
                    ),
                ),
            ],
            options={
                "db_table": "research_authors",
                "ordering": ["-paper_count"],
            },
        ),
    ]
