#!/usr/bin/env bash
# Idempotent repository bootstrap for the One9Founders backend (and the sibling
# frontend when it is present in the workspace). Safe to run repeatedly.
set -euo pipefail

# Resolve the backend repo root from this script's location (.cursor/install.sh).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKEND_DIR="$(dirname "$SCRIPT_DIR")"
cd "$BACKEND_DIR"

# uv (installed into ~/.local/bin) manages the pinned Python 3.11 toolchain.
export PATH="$HOME/.local/bin:$PATH"
if ! command -v uv >/dev/null 2>&1; then
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.local/bin:$PATH"
fi

echo "==> Ensuring Python 3.11 virtualenv"
uv python install 3.11
if [ ! -x "venv/bin/python" ]; then
  uv venv --python 3.11 venv
fi

echo "==> Installing CPU-only PyTorch (avoids ~7GB CUDA download)"
# shellcheck disable=SC1091
source venv/bin/activate
uv pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 \
  --index-url https://download.pytorch.org/whl/cpu

echo "==> Installing backend requirements"
uv pip install -r requirements.txt

echo "==> Ensuring backend .env exists"
if [ ! -f .env ]; then
  SECRET_KEY="$(python -c 'import secrets; print(secrets.token_urlsafe(50))')"
  cat > .env <<EOF
# Local development environment (generated by .cursor/install.sh)
DATABASE_NAME=one9data
DATABASE_USER=one9user
DATABASE_PASSWORD=one9pass
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5432

SECRET_KEY=${SECRET_KEY}
DEBUG=True
ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0

REDIS_URL=redis://127.0.0.1:6379/1

COWORKER_CLOUD_CLIENT_ID=one9founders-openworker-dev
COWORKER_CLOUD_PUBLIC_URL=http://127.0.0.1:8000
COWORKER_CLOUD_AUDIENCE=http://127.0.0.1:8000

FIRECRAWL_DISCOVERY_ENABLED=false

# Placeholder so the OpenAI client can be constructed at import time.
# Replace with a real key (add it as a Cloud Agent Secret) to enable AI features.
OPENAI_API_KEY=${OPENAI_API_KEY:-sk-local-dev-placeholder}
EOF
  echo "    wrote .env"
else
  echo "    .env already present, leaving it untouched"
fi

# ---- Frontend (sibling repo, only when checked out into the workspace) -------
FRONTEND_DIR="$(cd "$BACKEND_DIR/.." && pwd)/frontend"
if [ -d "$FRONTEND_DIR" ]; then
  echo "==> Installing frontend dependencies"
  cd "$FRONTEND_DIR"
  npm install
  if [ -f .env.local ] && ! grep -q "127.0.0.1:8000" .env.local; then
    # Point the frontend at the local backend for full-stack development.
    sed -i 's#^NEXT_PUBLIC_API_URL=.*#NEXT_PUBLIC_API_URL=http://127.0.0.1:8000#' .env.local
    echo "    pointed NEXT_PUBLIC_API_URL at local backend"
  fi
else
  echo "==> Frontend repo not present in workspace; skipping frontend install"
fi

echo "==> install.sh complete"
