import logging

from django.core.management.base import BaseCommand
from django.utils.text import slugify

from rag_directory.models import RagTool

logger = logging.getLogger(__name__)

SEED_DATA = [
    # === Vector Databases (35) ===
    {
        "name": "Pinecone",
        "description": "Fully managed vector database for high-performance similarity search at scale.",
        "website_url": "https://www.pinecone.io",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex", "haystack"],
    },
    {
        "name": "Qdrant",
        "description": "Open-source vector similarity search engine with extended filtering support.",
        "website_url": "https://qdrant.tech",
        "github_url": "https://github.com/qdrant/qdrant",
        "github_repo": "qdrant/qdrant",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "rust", "go"],
        "integrations": ["langchain", "llamaindex", "haystack"],
    },
    {
        "name": "Weaviate",
        "description": "Open-source vector database with built-in ML model integrations for vectorization.",
        "website_url": "https://weaviate.io",
        "github_url": "https://github.com/weaviate/weaviate",
        "github_repo": "weaviate/weaviate",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "go", "java"],
        "integrations": ["langchain", "llamaindex", "haystack"],
    },
    {
        "name": "Milvus",
        "description": "Open-source vector database built for scalable similarity search and AI applications.",
        "website_url": "https://milvus.io",
        "github_url": "https://github.com/milvus-io/milvus",
        "github_repo": "milvus-io/milvus",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex", "haystack"],
    },
    {
        "name": "Zilliz Cloud",
        "description": "Managed cloud service for Milvus with enterprise features and support.",
        "website_url": "https://zilliz.com",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Chroma",
        "description": "Open-source embedding database designed for AI-native applications.",
        "website_url": "https://www.trychroma.com",
        "github_url": "https://github.com/chroma-core/chroma",
        "github_repo": "chroma-core/chroma",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted", "embedded"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "pgvector",
        "description": "Open-source PostgreSQL extension for vector similarity search.",
        "website_url": "https://github.com/pgvector/pgvector",
        "github_url": "https://github.com/pgvector/pgvector",
        "github_repo": "pgvector/pgvector",
        "category": "vector_db",
        "pricing_model": "free",
        "deployment_options": ["self_hosted", "embedded"],
        "sdk_languages": ["python", "javascript", "ruby", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "LanceDB",
        "description": "Serverless vector database for AI applications with built-in storage.",
        "website_url": "https://lancedb.com",
        "github_url": "https://github.com/lancedb/lancedb",
        "github_repo": "lancedb/lancedb",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted", "embedded"],
        "sdk_languages": ["python", "javascript", "rust"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Turbopuffer",
        "description": "Serverless vector database optimized for low-latency search at scale.",
        "website_url": "https://turbopuffer.com",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain"],
    },
    {
        "name": "Vespa",
        "description": "Open-source big data serving engine for real-time vector search and ranking.",
        "website_url": "https://vespa.ai",
        "github_url": "https://github.com/vespa-engine/vespa",
        "github_repo": "vespa-engine/vespa",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "java"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "MongoDB Atlas Vector Search",
        "description": "Vector search capability built into MongoDB Atlas for AI-powered applications.",
        "website_url": "https://www.mongodb.com/products/platform/atlas-vector-search",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java", "go", "csharp"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Elasticsearch",
        "description": "Distributed search and analytics engine with dense vector search capabilities.",
        "website_url": "https://www.elastic.co/elasticsearch",
        "github_url": "https://github.com/elastic/elasticsearch",
        "github_repo": "elastic/elasticsearch",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go", "ruby"],
        "integrations": ["langchain", "llamaindex", "haystack"],
    },
    {
        "name": "Redis Vector",
        "description": "Redis Stack with vector similarity search for real-time AI applications.",
        "website_url": "https://redis.io/docs/interact/search-and-query/",
        "github_url": "https://github.com/redis/redis",
        "github_repo": "redis/redis",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Supabase pgvector",
        "description": "Managed PostgreSQL with pgvector for vector similarity search in Supabase.",
        "website_url": "https://supabase.com/vector",
        "github_url": "https://github.com/supabase/supabase",
        "github_repo": "supabase/supabase",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Neon pgvector",
        "description": "Serverless PostgreSQL with pgvector for vector search workloads.",
        "website_url": "https://neon.tech",
        "github_url": "https://github.com/neondatabase/neon",
        "github_repo": "neondatabase/neon",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "SingleStore",
        "description": "Distributed SQL database with built-in vector search for real-time analytics.",
        "website_url": "https://www.singlestore.com",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java"],
        "integrations": ["langchain"],
    },
    {
        "name": "ClickHouse",
        "description": "Column-oriented DBMS with vector search support for analytical workloads.",
        "website_url": "https://clickhouse.com",
        "github_url": "https://github.com/ClickHouse/ClickHouse",
        "github_repo": "ClickHouse/ClickHouse",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain"],
    },
    {
        "name": "DuckDB",
        "description": "In-process analytical database with vector similarity search extensions.",
        "website_url": "https://duckdb.org",
        "github_url": "https://github.com/duckdb/duckdb",
        "github_repo": "duckdb/duckdb",
        "category": "vector_db",
        "pricing_model": "free",
        "deployment_options": ["embedded"],
        "sdk_languages": ["python", "javascript", "java", "rust"],
        "integrations": ["langchain"],
    },
    {
        "name": "CozoDB",
        "description": "Hybrid relational-graph-vector database for next-gen AI applications.",
        "website_url": "https://www.cozodb.org",
        "github_url": "https://github.com/cozodb/cozo",
        "github_repo": "cozodb/cozo",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted", "embedded"],
        "sdk_languages": ["python", "javascript", "rust"],
        "integrations": [],
    },
    {
        "name": "Vald",
        "description": "Highly scalable distributed vector search engine for cloud-native architectures.",
        "website_url": "https://vald.vdaas.org",
        "github_url": "https://github.com/vdaas/vald",
        "github_repo": "vdaas/vald",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "go", "java"],
        "integrations": [],
    },
    {
        "name": "Deep Lake",
        "description": "Database for AI with native support for multi-modal data and vector search.",
        "website_url": "https://www.deeplake.ai",
        "github_url": "https://github.com/activeloopai/deeplake",
        "github_repo": "activeloopai/deeplake",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Marqo",
        "description": "End-to-end vector search engine with built-in ML model inference.",
        "website_url": "https://www.marqo.ai",
        "github_url": "https://github.com/marqo-ai/marqo",
        "github_repo": "marqo-ai/marqo",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "Typesense",
        "description": "Fast, typo-tolerant search engine with vector search capabilities.",
        "website_url": "https://typesense.org",
        "github_url": "https://github.com/typesense/typesense",
        "github_repo": "typesense/typesense",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "ruby", "php"],
        "integrations": ["langchain"],
    },
    {
        "name": "OpenSearch",
        "description": "Community-driven search and analytics suite with vector search support.",
        "website_url": "https://opensearch.org",
        "github_url": "https://github.com/opensearch-project/OpenSearch",
        "github_repo": "opensearch-project/OpenSearch",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "haystack"],
    },
    {
        "name": "Oracle AI Vector Search",
        "description": "Vector search capabilities integrated into Oracle Database for enterprise AI.",
        "website_url": "https://www.oracle.com/database/ai-vector-search/",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "java"],
        "integrations": ["langchain"],
    },
    {
        "name": "Azure AI Search",
        "description": "Microsoft's cloud search service with vector search and semantic ranking.",
        "website_url": "https://azure.microsoft.com/en-us/products/ai-services/ai-search",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java", "csharp"],
        "integrations": ["langchain", "llamaindex", "semantic-kernel"],
    },
    {
        "name": "Google Vertex AI Vector Search",
        "description": "Google Cloud's managed vector search for high-scale similarity matching.",
        "website_url": "https://cloud.google.com/vertex-ai/docs/vector-search/overview",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Amazon OpenSearch Serverless",
        "description": "Serverless vector search from AWS for large-scale similarity matching.",
        "website_url": "https://aws.amazon.com/opensearch-service/serverless-vector-engine/",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java"],
        "integrations": ["langchain"],
    },
    {
        "name": "Alibaba AnalyticDB",
        "description": "Cloud-native data warehouse with built-in vector analysis for AI applications.",
        "website_url": "https://www.alibabacloud.com/product/analyticdb-for-postgresql",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "java"],
        "integrations": [],
    },
    {
        "name": "TiDB Vector",
        "description": "Distributed SQL database with native vector search for AI workloads.",
        "website_url": "https://www.pingcap.com/tidb-serverless/",
        "github_url": "https://github.com/pingcap/tidb",
        "github_repo": "pingcap/tidb",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "StarRocks",
        "description": "Sub-second analytics database with vector indexing for AI-powered queries.",
        "website_url": "https://www.starrocks.io",
        "github_url": "https://github.com/StarRocks/starrocks",
        "github_repo": "StarRocks/starrocks",
        "category": "vector_db",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "java"],
        "integrations": [],
    },
    {
        "name": "Aerospike",
        "description": "Real-time data platform with vector search for sub-millisecond AI applications.",
        "website_url": "https://aerospike.com",
        "github_url": "https://github.com/aerospike/aerospike-server",
        "github_repo": "aerospike/aerospike-server",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "java", "go", "csharp"],
        "integrations": ["langchain"],
    },
    {
        "name": "DataStax Astra",
        "description": "Managed Cassandra-based database with vector search for GenAI apps.",
        "website_url": "https://www.datastax.com/products/datastax-astra",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Neo4j Vector",
        "description": "Graph database with vector search for knowledge graph-powered RAG.",
        "website_url": "https://neo4j.com",
        "github_url": "https://github.com/neo4j/neo4j",
        "github_repo": "neo4j/neo4j",
        "category": "vector_db",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "javascript", "java", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Rockset",
        "description": "Real-time analytics database with vector search for hybrid queries.",
        "website_url": "https://rockset.com",
        "github_url": "",
        "github_repo": "",
        "category": "vector_db",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "java"],
        "integrations": ["langchain"],
    },
    # === RAG Frameworks (25) ===
    {
        "name": "LangChain",
        "description": "Framework for developing applications powered by language models with composable chains.",
        "website_url": "https://www.langchain.com",
        "github_url": "https://github.com/langchain-ai/langchain",
        "github_repo": "langchain-ai/langchain",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["openai", "anthropic", "huggingface"],
    },
    {
        "name": "LlamaIndex",
        "description": "Data framework for LLM applications to ingest, structure, and access private data.",
        "website_url": "https://www.llamaindex.ai",
        "github_url": "https://github.com/run-llama/llama_index",
        "github_repo": "run-llama/llama_index",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["openai", "anthropic", "huggingface"],
    },
    {
        "name": "Haystack",
        "description": "End-to-end NLP framework for building production-ready RAG pipelines.",
        "website_url": "https://haystack.deepset.ai",
        "github_url": "https://github.com/deepset-ai/haystack",
        "github_repo": "deepset-ai/haystack",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["openai", "huggingface", "elasticsearch"],
    },
    {
        "name": "Verba",
        "description": "Golden RAGtriever - open-source RAG application powered by Weaviate.",
        "website_url": "https://github.com/weaviate/Verba",
        "github_url": "https://github.com/weaviate/Verba",
        "github_repo": "weaviate/Verba",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["weaviate", "openai"],
    },
    {
        "name": "Mem0",
        "description": "Memory layer for AI assistants and agents with long-term memory management.",
        "website_url": "https://mem0.ai",
        "github_url": "https://github.com/mem0ai/mem0",
        "github_repo": "mem0ai/mem0",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["openai", "langchain"],
    },
    {
        "name": "Embedchain",
        "description": "Framework to create LLM-powered bots over any dataset with minimal code.",
        "website_url": "https://github.com/embedchain/embedchain",
        "github_url": "https://github.com/embedchain/embedchain",
        "github_repo": "embedchain/embedchain",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["openai", "langchain"],
    },
    {
        "name": "RAGatouille",
        "description": "Library for easy fine-tuning and inference of ColBERT-based late interaction retrieval.",
        "website_url": "https://github.com/bclavie/RAGatouille",
        "github_url": "https://github.com/bclavie/RAGatouille",
        "github_repo": "bclavie/RAGatouille",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "txtai",
        "description": "All-in-one embeddings database for semantic search, RAG, and LLM workflows.",
        "website_url": "https://neuml.github.io/txtai/",
        "github_url": "https://github.com/neuml/txtai",
        "github_repo": "neuml/txtai",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": [],
    },
    {
        "name": "Canopy",
        "description": "Open-source RAG framework by Pinecone for building chat and Q&A applications.",
        "website_url": "https://github.com/pinecone-io/canopy",
        "github_url": "https://github.com/pinecone-io/canopy",
        "github_repo": "pinecone-io/canopy",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["pinecone", "openai"],
    },
    {
        "name": "AutoRAG",
        "description": "AutoML tool for finding optimal RAG pipeline for your data.",
        "website_url": "https://github.com/Marker-Inc-Korea/AutoRAG",
        "github_url": "https://github.com/Marker-Inc-Korea/AutoRAG",
        "github_repo": "Marker-Inc-Korea/AutoRAG",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "FlashRAG",
        "description": "Python toolkit for efficient RAG research with modular components.",
        "website_url": "https://github.com/RUC-NLPIR/FlashRAG",
        "github_url": "https://github.com/RUC-NLPIR/FlashRAG",
        "github_repo": "RUC-NLPIR/FlashRAG",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["huggingface"],
    },
    {
        "name": "RAGAS",
        "description": "Evaluation framework for Retrieval Augmented Generation pipelines.",
        "website_url": "https://ragas.io",
        "github_url": "https://github.com/explodinggradients/ragas",
        "github_repo": "explodinggradients/ragas",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "LangGraph",
        "description": "Library for building stateful, multi-actor LLM applications as graphs.",
        "website_url": "https://www.langchain.com/langgraph",
        "github_url": "https://github.com/langchain-ai/langgraph",
        "github_repo": "langchain-ai/langgraph",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain"],
    },
    {
        "name": "CrewAI",
        "description": "Framework for orchestrating role-playing autonomous AI agents.",
        "website_url": "https://www.crewai.com",
        "github_url": "https://github.com/crewAIInc/crewAI",
        "github_repo": "crewAIInc/crewAI",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "openai"],
    },
    {
        "name": "Semantic Kernel",
        "description": "Microsoft's SDK for integrating LLMs into apps with enterprise patterns.",
        "website_url": "https://learn.microsoft.com/en-us/semantic-kernel/",
        "github_url": "https://github.com/microsoft/semantic-kernel",
        "github_repo": "microsoft/semantic-kernel",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "csharp", "java"],
        "integrations": ["openai", "azure"],
    },
    {
        "name": "Spring AI",
        "description": "Spring-based framework for building AI applications in Java/Kotlin.",
        "website_url": "https://spring.io/projects/spring-ai",
        "github_url": "https://github.com/spring-projects/spring-ai",
        "github_repo": "spring-projects/spring-ai",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["java"],
        "integrations": ["openai", "huggingface"],
    },
    {
        "name": "Dify",
        "description": "Open-source LLM app development platform with visual RAG pipeline builder.",
        "website_url": "https://dify.ai",
        "github_url": "https://github.com/langgenius/dify",
        "github_repo": "langgenius/dify",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["openai", "anthropic"],
    },
    {
        "name": "Flowise",
        "description": "Drag-and-drop UI for building customized LLM and RAG flows.",
        "website_url": "https://flowiseai.com",
        "github_url": "https://github.com/FlowiseAI/Flowise",
        "github_repo": "FlowiseAI/Flowise",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["javascript"],
        "integrations": ["langchain", "openai"],
    },
    {
        "name": "Langflow",
        "description": "Visual framework for building multi-agent and RAG applications with drag-and-drop.",
        "website_url": "https://www.langflow.org",
        "github_url": "https://github.com/langflow-ai/langflow",
        "github_repo": "langflow-ai/langflow",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "openai"],
    },
    {
        "name": "n8n AI Nodes",
        "description": "Workflow automation platform with AI/RAG nodes for building AI pipelines.",
        "website_url": "https://n8n.io",
        "github_url": "https://github.com/n8n-io/n8n",
        "github_repo": "n8n-io/n8n",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["javascript"],
        "integrations": ["openai", "pinecone", "qdrant"],
    },
    {
        "name": "Unstructured",
        "description": "Open-source library for pre-processing documents for RAG pipelines.",
        "website_url": "https://unstructured.io",
        "github_url": "https://github.com/Unstructured-IO/unstructured",
        "github_repo": "Unstructured-IO/unstructured",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Docling",
        "description": "IBM's document parsing library for converting PDFs and docs into structured data.",
        "website_url": "https://github.com/DS4SD/docling",
        "github_url": "https://github.com/DS4SD/docling",
        "github_repo": "DS4SD/docling",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "LiteLLM",
        "description": "Unified interface for calling 100+ LLM APIs in the OpenAI format.",
        "website_url": "https://litellm.ai",
        "github_url": "https://github.com/BerriAI/litellm",
        "github_repo": "BerriAI/litellm",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["openai", "anthropic", "langchain"],
    },
    {
        "name": "vLLM",
        "description": "High-throughput LLM serving engine with PagedAttention for efficient inference.",
        "website_url": "https://vllm.ai",
        "github_url": "https://github.com/vllm-project/vllm",
        "github_repo": "vllm-project/vllm",
        "category": "rag_framework",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Ollama",
        "description": "Run open-source LLMs locally with a simple command-line interface.",
        "website_url": "https://ollama.com",
        "github_url": "https://github.com/ollama/ollama",
        "github_repo": "ollama/ollama",
        "category": "rag_framework",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "javascript", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    # === Embedding Models (50) ===
    {
        "name": "OpenAI text-embedding-3-small",
        "description": "OpenAI's latest small embedding model with strong performance at low cost.",
        "website_url": "https://platform.openai.com/docs/guides/embeddings",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "OpenAI text-embedding-3-large",
        "description": "OpenAI's most capable embedding model for maximum retrieval accuracy.",
        "website_url": "https://platform.openai.com/docs/guides/embeddings",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Cohere Embed v3",
        "description": "Multilingual embedding model with support for 100+ languages.",
        "website_url": "https://cohere.com/embed",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Google text-embedding-004",
        "description": "Google's latest text embedding model via Vertex AI with 768 dimensions.",
        "website_url": "https://cloud.google.com/vertex-ai/generative-ai/docs/embeddings/get-text-embeddings",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Voyage AI voyage-3",
        "description": "High-performance embedding model optimized for retrieval and RAG.",
        "website_url": "https://www.voyageai.com",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "BGE-M3",
        "description": "Multi-functional, multi-lingual, multi-granularity text embedding model by BAAI.",
        "website_url": "https://huggingface.co/BAAI/bge-m3",
        "github_url": "https://github.com/FlagOpen/FlagEmbedding",
        "github_repo": "FlagOpen/FlagEmbedding",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "E5-Mistral-7B",
        "description": "Decoder-only embedding model achieving state-of-the-art on MTEB benchmarks.",
        "website_url": "https://huggingface.co/intfloat/e5-mistral-7b-instruct",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "GTE-Qwen2",
        "description": "General Text Embedding model based on Qwen2 architecture by Alibaba.",
        "website_url": "https://huggingface.co/Alibaba-NLP/gte-Qwen2-7B-instruct",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "Nomic Embed Text v1.5",
        "description": "Open-source, auditable embedding model with competitive MTEB performance.",
        "website_url": "https://www.nomic.ai",
        "github_url": "https://github.com/nomic-ai/nomic",
        "github_repo": "nomic-ai/nomic",
        "category": "embedding_model",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Jina Embeddings v3",
        "description": "Task-specific embedding model with support for passages, queries, and code.",
        "website_url": "https://jina.ai/embeddings",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "all-MiniLM-L6-v2",
        "description": "Lightweight sentence-transformers model optimized for semantic similarity.",
        "website_url": "https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2",
        "github_url": "https://github.com/UKPLab/sentence-transformers",
        "github_repo": "UKPLab/sentence-transformers",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "bge-large-en-v1.5",
        "description": "BAAI's general embedding model achieving top performance on English benchmarks.",
        "website_url": "https://huggingface.co/BAAI/bge-large-en-v1.5",
        "github_url": "https://github.com/FlagOpen/FlagEmbedding",
        "github_repo": "FlagOpen/FlagEmbedding",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "UAE-Large-V1",
        "description": "Universal AnglE Embedding model for high-quality text embeddings.",
        "website_url": "https://huggingface.co/WhereIsAI/UAE-Large-V1",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "mxbai-embed-large-v1",
        "description": "Mixedbread's open-source embedding model with strong retrieval performance.",
        "website_url": "https://www.mixedbread.ai",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Instructor",
        "description": "Instruction-finetuned text embedding model for customizable embeddings.",
        "website_url": "https://huggingface.co/hkunlp/instructor-xl",
        "github_url": "https://github.com/xlang-ai/instructor-embedding",
        "github_repo": "xlang-ai/instructor-embedding",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "SFR-Embedding-Mistral",
        "description": "Salesforce's Mistral-based embedding model for retrieval tasks.",
        "website_url": "https://huggingface.co/Salesforce/SFR-Embedding-Mistral",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "Snowflake Arctic Embed",
        "description": "Snowflake's family of text embedding models optimized for retrieval.",
        "website_url": "https://huggingface.co/Snowflake/snowflake-arctic-embed-l",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "Ollama Embeddings",
        "description": "Run embedding models locally through Ollama for privacy-first RAG.",
        "website_url": "https://ollama.com",
        "github_url": "https://github.com/ollama/ollama",
        "github_repo": "ollama/ollama",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python", "javascript", "go"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Amazon Titan Embeddings",
        "description": "AWS Bedrock embedding model for enterprise RAG applications.",
        "website_url": "https://aws.amazon.com/bedrock/titan/",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain"],
    },
    {
        "name": "Azure OpenAI Embeddings",
        "description": "OpenAI embedding models hosted on Azure with enterprise compliance.",
        "website_url": "https://azure.microsoft.com/en-us/products/ai-services/openai-service",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript", "csharp"],
        "integrations": ["langchain", "llamaindex", "semantic-kernel"],
    },
    {
        "name": "Fastembed",
        "description": "Lightweight Python library for fast text embedding generation by Qdrant.",
        "website_url": "https://qdrant.github.io/fastembed/",
        "github_url": "https://github.com/qdrant/fastembed",
        "github_repo": "qdrant/fastembed",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["qdrant", "langchain"],
    },
    {
        "name": "TEI (Text Embeddings Inference)",
        "description": "Hugging Face's high-performance embedding inference server.",
        "website_url": "https://huggingface.co/docs/text-embeddings-inference",
        "github_url": "https://github.com/huggingface/text-embeddings-inference",
        "github_repo": "huggingface/text-embeddings-inference",
        "category": "embedding_model",
        "pricing_model": "open_source",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python", "rust"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Infinity Embedding Server",
        "description": "MIT-licensed high-throughput embedding inference server.",
        "website_url": "https://github.com/michaelfeil/infinity",
        "github_url": "https://github.com/michaelfeil/infinity",
        "github_repo": "michaelfeil/infinity",
        "category": "embedding_model",
        "pricing_model": "open_source",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "Mistral Embed",
        "description": "Mistral AI's embedding model with 1024 dimensions for retrieval.",
        "website_url": "https://docs.mistral.ai/capabilities/embeddings/",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Stella-EN-1.5B",
        "description": "Compact yet powerful embedding model optimized for English text retrieval.",
        "website_url": "https://huggingface.co/dunzhang/stella_en_1.5B_v5",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "NV-Embed-v2",
        "description": "NVIDIA's generalist embedding model for retrieval and classification tasks.",
        "website_url": "https://huggingface.co/nvidia/NV-Embed-v2",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "gte-large-en-v1.5",
        "description": "Alibaba's general text embedding model with 1024 dimensions.",
        "website_url": "https://huggingface.co/Alibaba-NLP/gte-large-en-v1.5",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "CLIP (OpenAI)",
        "description": "Multimodal model for text and image embeddings in shared vector space.",
        "website_url": "https://openai.com/research/clip",
        "github_url": "https://github.com/openai/CLIP",
        "github_repo": "openai/CLIP",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "SigLIP",
        "description": "Google's improved CLIP-like model for vision-language understanding.",
        "website_url": "https://huggingface.co/google/siglip-base-patch16-224",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": [],
    },
    {
        "name": "ColBERT v2",
        "description": "Late-interaction retrieval model enabling fine-grained relevance matching.",
        "website_url": "https://github.com/stanford-futuredata/ColBERT",
        "github_url": "https://github.com/stanford-futuredata/ColBERT",
        "github_repo": "stanford-futuredata/ColBERT",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["llamaindex"],
    },
    {
        "name": "DRAGON+",
        "description": "LinkedIn's generalized dense retriever with diverse augmentation.",
        "website_url": "https://huggingface.co/facebook/dragon-plus-query-encoder",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": [],
    },
    {
        "name": "Cohere Embed v3 Multilingual",
        "description": "Multilingual embedding model supporting 100+ languages for global RAG.",
        "website_url": "https://cohere.com/embed",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "multilingual-e5-large",
        "description": "Multilingual embedding model supporting 100 languages with strong performance.",
        "website_url": "https://huggingface.co/intfloat/multilingual-e5-large",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "bge-reranker-v2-m3",
        "description": "BAAI's cross-encoder reranker model for improving retrieval quality.",
        "website_url": "https://huggingface.co/BAAI/bge-reranker-v2-m3",
        "github_url": "https://github.com/FlagOpen/FlagEmbedding",
        "github_repo": "FlagOpen/FlagEmbedding",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Cohere Rerank v3",
        "description": "Reranking model to improve search relevance for RAG applications.",
        "website_url": "https://cohere.com/rerank",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "Jina Reranker v2",
        "description": "Lightweight reranker model for improving RAG retrieval accuracy.",
        "website_url": "https://jina.ai/reranker",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["langchain", "llamaindex"],
    },
    {
        "name": "voyage-code-3",
        "description": "Voyage AI's embedding model specifically optimized for code retrieval.",
        "website_url": "https://www.voyageai.com",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python"],
        "integrations": ["langchain"],
    },
    {
        "name": "WhereIsAI UAE-Code-Large-V1",
        "description": "Code-specific embedding model for code search and similarity tasks.",
        "website_url": "https://huggingface.co/WhereIsAI/UAE-Code-Large-V1",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "free",
        "deployment_options": ["self_hosted"],
        "sdk_languages": ["python"],
        "integrations": [],
    },
    {
        "name": "Jina ColBERT v2",
        "description": "Jina's late interaction model for efficient and accurate retrieval.",
        "website_url": "https://jina.ai",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "freemium",
        "deployment_options": ["cloud", "self_hosted"],
        "sdk_languages": ["python"],
        "integrations": ["llamaindex"],
    },
    {
        "name": "OpenAI text-embedding-ada-002",
        "description": "OpenAI's legacy embedding model, widely used and well-supported.",
        "website_url": "https://platform.openai.com/docs/guides/embeddings",
        "github_url": "",
        "github_repo": "",
        "category": "embedding_model",
        "pricing_model": "paid",
        "deployment_options": ["cloud"],
        "sdk_languages": ["python", "javascript"],
        "integrations": ["langchain", "llamaindex"],
    },
]


class Command(BaseCommand):
    help = "Seed the RAG & Vector DB directory with initial tool data"

    def add_arguments(self, parser):
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Clear existing data before seeding",
        )

    def handle(self, *args, **options):
        if options["clear"]:
            count = RagTool.objects.count()
            RagTool.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Cleared {count} existing tools"))

        created = 0
        skipped = 0

        for tool_data in SEED_DATA:
            slug = slugify(tool_data["name"])

            if RagTool.objects.filter(slug=slug).exists():
                skipped += 1
                continue

            RagTool.objects.create(
                slug=slug,
                name=tool_data["name"],
                description=tool_data["description"],
                website_url=tool_data["website_url"],
                github_url=tool_data.get("github_url", ""),
                github_repo=tool_data.get("github_repo", ""),
                category=tool_data["category"],
                pricing_model=tool_data["pricing_model"],
                deployment_options=tool_data.get("deployment_options", []),
                sdk_languages=tool_data.get("sdk_languages", []),
                integrations=tool_data.get("integrations", []),
            )
            created += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {created} tools, skipped {skipped} duplicates. "
                f"Total: {RagTool.objects.count()}"
            )
        )
