# Generated by Django 6.0.3 on 2026-03-22 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToolSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=255, unique=True)),
                ("overall_score", models.FloatField(blank=True, null=True)),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("mixed", "Mixed"),
                            ("negative", "Negative"),
                            ("insufficient_data", "Insufficient Data"),
                        ],
                        default="insufficient_data",
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("source_count", models.IntegerField(default=0)),
                ("top_praises", models.JSONField(default=list)),
                ("top_complaints", models.JSONField(default=list)),
                ("red_flags", models.JSONField(default=list)),
                ("one_line_summary", models.TextField(blank=True)),
                ("was_corrected", models.BooleanField(default=False)),
                ("last_analysed", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Tool Sentiment",
            },
        ),
    ]
