# Generated by Django 5.2.9 on 2026-02-28 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AudienceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("landing_page_url", models.URLField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Audience Types",
                "db_table": "education_audience_types",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Icon class or emoji", max_length=100
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Course Categories",
                "db_table": "education_course_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[("college", "College"), ("corporate", "Corporate")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("organization", models.CharField(max_length=255)),
                ("role", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("estimated_batch_size", models.IntegerField(default=0)),
                ("preferred_timeline", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization Inquiry",
                "verbose_name_plural": "Organization Inquiries",
                "db_table": "education_organization_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Supports markdown"),
                ),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("featured_image", models.URLField(blank=True)),
                ("intro_video_url", models.URLField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("self_paced", "Self-Paced"),
                            ("cohort", "Cohort-Based"),
                            ("live", "Live"),
                            ("hybrid", "Hybrid"),
                        ],
                        db_index=True,
                        default="self_paced",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("coming_soon", "Coming Soon"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("duration_weeks", models.IntegerField(default=0)),
                ("hours_per_week", models.IntegerField(default=0)),
                ("total_lessons", models.IntegerField(default=0)),
                ("next_cohort_date", models.DateField(blank=True, null=True)),
                ("schedule_description", models.CharField(blank=True, max_length=300)),
                (
                    "whats_included",
                    models.JSONField(
                        blank=True, default=list, help_text="List of strings"
                    ),
                ),
                (
                    "tools_mentioned",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tool slugs"
                    ),
                ),
                (
                    "certificate_description",
                    models.CharField(
                        blank=True,
                        default="Certificate issued through IIT Bombay Educational Outreach",
                        max_length=500,
                    ),
                ),
                ("has_certificate", models.BooleanField(default=True)),
                ("language", models.CharField(default="English", max_length=50)),
                ("has_hindi_support", models.BooleanField(default=False)),
                (
                    "iitb_eo_link",
                    models.URLField(
                        blank=True, help_text="IIT Bombay EO link (internal only)"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("interest_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True, related_name="courses", to="education.audiencetype"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="courses",
                        to="education.coursecategory",
                    ),
                ),
            ],
            options={
                "db_table": "education_courses",
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseFAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=500)),
                ("answer", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="education.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course FAQ",
                "verbose_name_plural": "Course FAQs",
                "db_table": "education_course_faqs",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("duration_description", models.CharField(blank=True, max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="education.course",
                    ),
                ),
            ],
            options={
                "db_table": "education_course_modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("bio", models.TextField(blank=True)),
                ("short_bio", models.CharField(blank=True, max_length=300)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="education/instructors/"),
                ),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="instructor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "education_instructors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EducationWorkshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.IntegerField(default=60)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("webinar", "Webinar"),
                            ("workshop", "Workshop"),
                            ("corporate", "Corporate"),
                        ],
                        db_index=True,
                        default="webinar",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="upcoming",
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=100)),
                (
                    "meeting_link",
                    models.URLField(
                        blank=True, help_text="Internal only — not exposed in API"
                    ),
                ),
                ("recording_url", models.URLField(blank=True)),
                ("max_participants", models.IntegerField(default=0)),
                (
                    "learning_outcomes",
                    models.JSONField(
                        blank=True, default=list, help_text="List of outcome strings"
                    ),
                ),
                ("prerequisites", models.TextField(blank=True)),
                ("registration_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True,
                        related_name="workshops",
                        to="education.audiencetype",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshops",
                        to="education.coursecategory",
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshops",
                        to="education.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Workshop",
                "verbose_name_plural": "Education Workshops",
                "db_table": "education_workshops",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EducationGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "content",
                    models.TextField(blank=True, help_text="Supports markdown"),
                ),
                ("excerpt", models.CharField(blank=True, max_length=500)),
                ("featured_image", models.URLField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "In Review"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("read_time_minutes", models.IntegerField(default=0)),
                (
                    "tools_mentioned",
                    models.JSONField(
                        blank=True, default=list, help_text="List of tool slugs"
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("view_count", models.IntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audiences",
                    models.ManyToManyField(
                        blank=True, related_name="guides", to="education.audiencetype"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guides",
                        to="education.coursecategory",
                    ),
                ),
                (
                    "related_course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_guides",
                        to="education.course",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guides",
                        to="education.instructor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Education Guide",
                "verbose_name_plural": "Education Guides",
                "db_table": "education_guides",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="instructors",
            field=models.ManyToManyField(
                blank=True, related_name="courses", to="education.instructor"
            ),
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("students", "Students"),
                            ("professionals", "Professionals"),
                            ("entrepreneurs", "Entrepreneurs"),
                            ("organizations", "Organizations"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("hero_title", models.CharField(max_length=255)),
                ("hero_subtitle", models.TextField(blank=True)),
                ("hero_cta_text", models.CharField(blank=True, max_length=100)),
                ("hero_cta_url", models.URLField(blank=True)),
                ("hero_image", models.URLField(blank=True)),
                ("pitch_title", models.CharField(blank=True, max_length=255)),
                (
                    "pitch_content",
                    models.TextField(blank=True, help_text="Supports markdown"),
                ),
                (
                    "content_blocks",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Flexible content sections as JSON",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "featured_courses",
                    models.ManyToManyField(
                        blank=True, related_name="landing_pages", to="education.course"
                    ),
                ),
            ],
            options={
                "db_table": "education_landing_pages",
                "ordering": ["page_type"],
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("estimated_duration", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "audience",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_paths",
                        to="education.audiencetype",
                    ),
                ),
            ],
            options={
                "db_table": "education_learning_paths",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="CourseInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_page",
                    models.CharField(
                        blank=True,
                        help_text="URL where form was submitted",
                        max_length=500,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("current_role", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("forwarded_to_iitb", "Forwarded to IITB"),
                            ("enrolled", "Enrolled"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="education.course",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="education.educationworkshop",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="education.learningpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Inquiry",
                "verbose_name_plural": "Course Inquiries",
                "db_table": "education_course_inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "courses",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_path_modules",
                        to="education.course",
                    ),
                ),
                (
                    "guides",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_path_modules",
                        to="education.educationguide",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="education.learningpath",
                    ),
                ),
                (
                    "workshops",
                    models.ManyToManyField(
                        blank=True,
                        related_name="learning_path_modules",
                        to="education.educationworkshop",
                    ),
                ),
            ],
            options={
                "db_table": "education_learning_path_modules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("attended", models.BooleanField(default=False)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="education.educationworkshop",
                    ),
                ),
            ],
            options={
                "db_table": "education_workshop_registrations",
                "ordering": ["-registered_at"],
                "unique_together": {("email", "workshop")},
            },
        ),
    ]
