# Generated by Django 5.2.9 on 2026-03-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RagTool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("logo_url", models.URLField(blank=True)),
                ("description", models.TextField()),
                ("long_description", models.TextField(blank=True)),
                ("website_url", models.URLField()),
                ("docs_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("github_repo", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vector_db", "Vector Database"),
                            ("rag_framework", "RAG Framework"),
                            ("embedding_model", "Embedding Model"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pricing_model",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("freemium", "Freemium"),
                            ("paid", "Paid"),
                            ("open_source", "Open Source"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pricing_details", models.JSONField(blank=True, default=dict)),
                ("deployment_options", models.JSONField(default=list)),
                ("sdk_languages", models.JSONField(default=list)),
                ("integrations", models.JSONField(default=list)),
                ("specs", models.JSONField(blank=True, default=dict)),
                ("security_certs", models.JSONField(default=list)),
                ("rating_scores", models.JSONField(default=dict)),
                (
                    "overall_rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("deprecated", "Deprecated"),
                            ("stale", "Stale"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("github_stars", models.IntegerField(default=0)),
                ("github_forks", models.IntegerField(default=0)),
                ("last_commit_at", models.DateTimeField(blank=True, null=True)),
                ("latest_release", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "rag_tools",
                "ordering": ["-overall_rating", "-github_stars"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="rag_tools_categor_2fd8c8_idx",
                    ),
                    models.Index(
                        fields=["pricing_model"], name="rag_tools_pricing_94d62d_idx"
                    ),
                    models.Index(
                        fields=["-github_stars"], name="rag_tools_github__a1d597_idx"
                    ),
                    models.Index(
                        fields=["-overall_rating"], name="rag_tools_overall_45e999_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GitHubSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("open_issues", models.IntegerField(default=0)),
                ("contributors", models.IntegerField(default=0)),
                ("last_commit_at", models.DateTimeField(null=True)),
                ("latest_release", models.CharField(blank=True, max_length=100)),
                ("snapshot_date", models.DateField()),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_snapshots",
                        to="rag_directory.ragtool",
                    ),
                ),
            ],
            options={
                "db_table": "github_snapshots",
                "ordering": ["-snapshot_date"],
                "unique_together": {("tool", "snapshot_date")},
            },
        ),
    ]
